SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
INNER JOIN SKILLCODES B 
ON B.NAME IN ('Python','C#') AND A.SKILL_CODE & B.CODE = B.CODE
# B.CODE를 포함하고 있으려면 교집합이 B.CODE여야 하니까
GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID